server:
  port: 80
spring:
  application:
    name: RegiApplication
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      #mysql8
##      url: jdbc:mysql://192.168.187.131:3306/reggie_take_out?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      url: jdbc:mysql://192.168.187.131:3306/reggie_take_out?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#      username: root
#      password: 123456
  shardingsphere:
    datasource:
      names:
        master,slave
        # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.187.131:3306/reggie_take_out?characterEncoding=utf-8
        username: root
        password: 123456
        # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.187.132:3306/reggie_take_out?characterEncoding=utf-8
        username: root
        password: 123456
    masterslave:
      # 读写分离配置
      load-balance-algorithm-type: round_robin
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL显示，默认false--控制台输出SQL

  main:
    allow-bean-definition-overriding: true #在配置文件中配置允许bean定义覆盖配置项

  redis:
    host: localhost
    port: 6379
    #password: 123456
    database: 1
  cache:
    redis:
      time-to-live: 1800000 #缓存过期时间
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
#自定义上传的文件的保存位置
reggie:
  path: D:\testReggieImg\